---
title: "Wellspring Data Analysis Project Proposal"
author: "Jingtian Hu - (Instructors: Nathalie Moon and Morris Greenberg)"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(clock)
data <- read_csv("v1_wrangled_Member_Background.csv")
```

```{r}
added_dates_data <- data |>
     mutate(
         starting_date = date_build(member_start_year, member_start_month, ),
         ending_date = date_build(2025, 2, 1),
     )
added_dates_data <- added_dates_data |>
    mutate(last_service_date = case_when(is.na(last_service_date_year) ~ starting_date,
                                       !is.na(last_service_date_year) ~ date_build(last_service_date_year, last_service_date_month, last_service_date_day)))

added_membership_duration <- added_dates_data |>
  mutate(mem_duration_month = (ending_date - starting_date) |> as.numeric() / 30)
final_data <- added_membership_duration |> 
  mutate(present_service_deliveries_per_month = number_of_present_service_deliveries / mem_duration_month,
         time_since_last_service = (ending_date - last_service_date) |> as.numeric())
```

```{r}
model <- lm(present_service_deliveries_per_month~ (age_years + gender + types_of_cancer + how_have_you_heard_of_wellspring) * time_since_last_service, data=final_data)

```